### ISSUE TITLE
Support for %autochangelog and %autorelease macros

### ISSUE THREAD

**Issue by chriskilding** [essentialkaos/perfecto#78]
### Feature Request

**Proposal:**

Perfecto should understand the `%autochangelog` and `%autorelease` macros, which are recent additions to the .spec file format.

**Current behavior:**

1. Write a .spec file that contains the `%autochangelog` and/or `%autorelease` macros
2. Run Perfecto. 
3. You see the following output:

```
••• Error (2)                                                                          
│
│ [3] (PF3) Release tag must contains %{?dist} as part of release
│ Release:        %autorelease
│
│ [40] (PF10) Symbol % must be escaped by another % (i.e % → %%)
│ %autochangelog
```

**Desired behavior:**

Perfecto should understand the `%autochangelog` and `%autorelease` macros, and not throw an error about them.

**Use case:**

These macros are used by the `rpmautospec` tool when doing automatic packaging from an upstream repo.

Additionally, Fedora is adopting `rpmautospec` (https://fedoraproject.org/wiki/Changes/rpmautospec) in the Packit build service. This would mean that packages built with Packit will presumably start to use these macros soon.

**Comment by andyone** [comment]
@chriskilding Hi! 

Thanks for the detailed info. I have added support for these macroses to the latest release of _perfecto_ (#79).

I will release this version in 1-2 days.
